# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, email: str=None, firstname: str=None, lastname: str=None, password: str=None, date_of_birth: str=None, points: int=None, content_filter: bool=False, is_admin: bool=False):  # noqa: E501
        """User - a model defined in Swagger

        :param id: The id of this User.  # noqa: E501
        :type id: int
        :param email: The email of this User.  # noqa: E501
        :type email: str
        :param firstname: The firstname of this User.  # noqa: E501
        :type firstname: str
        :param lastname: The lastname of this User.  # noqa: E501
        :type lastname: str
        :param password: The password of this User.  # noqa: E501
        :type password: str
        :param date_of_birth: The date_of_birth of this User.  # noqa: E501
        :type date_of_birth: str
        :param points: The points of this User.  # noqa: E501
        :type points: int
        :param content_filter: The content_filter of this User.  # noqa: E501
        :type content_filter: bool
        :param is_admin: The is_admin of this User.  # noqa: E501
        :type is_admin: bool
        """
        self.swagger_types = {
            'id': int,
            'email': str,
            'firstname': str,
            'lastname': str,
            'password': str,
            'date_of_birth': str,
            'points': int,
            'content_filter': bool,
            'is_admin': bool
        }

        self.attribute_map = {
            'id': 'id',
            'email': 'email',
            'firstname': 'firstname',
            'lastname': 'lastname',
            'password': 'password',
            'date_of_birth': 'date_of_birth',
            'points': 'points',
            'content_filter': 'content_filter',
            'is_admin': 'is_admin'
        }

        self._id = id
        self._email = email
        self._firstname = firstname
        self._lastname = lastname
        self._password = password
        self._date_of_birth = date_of_birth
        self._points = points
        self._content_filter = content_filter
        self._is_admin = is_admin

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this User.


        :return: The id of this User.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this User.


        :param id: The id of this User.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def email(self) -> str:
        """Gets the email of this User.


        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this User.


        :param email: The email of this User.
        :type email: str
        """

        self._email = email

    @property
    def firstname(self) -> str:
        """Gets the firstname of this User.


        :return: The firstname of this User.
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname: str):
        """Sets the firstname of this User.


        :param firstname: The firstname of this User.
        :type firstname: str
        """

        self._firstname = firstname

    @property
    def lastname(self) -> str:
        """Gets the lastname of this User.


        :return: The lastname of this User.
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname: str):
        """Sets the lastname of this User.


        :param lastname: The lastname of this User.
        :type lastname: str
        """

        self._lastname = lastname

    @property
    def password(self) -> str:
        """Gets the password of this User.


        :return: The password of this User.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this User.


        :param password: The password of this User.
        :type password: str
        """

        self._password = password

    @property
    def date_of_birth(self) -> str:
        """Gets the date_of_birth of this User.


        :return: The date_of_birth of this User.
        :rtype: str
        """
        return self._date_of_birth

    @date_of_birth.setter
    def date_of_birth(self, date_of_birth: str):
        """Sets the date_of_birth of this User.


        :param date_of_birth: The date_of_birth of this User.
        :type date_of_birth: str
        """

        self._date_of_birth = date_of_birth

    @property
    def points(self) -> int:
        """Gets the points of this User.


        :return: The points of this User.
        :rtype: int
        """
        return self._points

    @points.setter
    def points(self, points: int):
        """Sets the points of this User.


        :param points: The points of this User.
        :type points: int
        """

        self._points = points

    @property
    def content_filter(self) -> bool:
        """Gets the content_filter of this User.


        :return: The content_filter of this User.
        :rtype: bool
        """
        return self._content_filter

    @content_filter.setter
    def content_filter(self, content_filter: bool):
        """Sets the content_filter of this User.


        :param content_filter: The content_filter of this User.
        :type content_filter: bool
        """

        self._content_filter = content_filter

    @property
    def is_admin(self) -> bool:
        """Gets the is_admin of this User.


        :return: The is_admin of this User.
        :rtype: bool
        """
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin: bool):
        """Sets the is_admin of this User.


        :param is_admin: The is_admin of this User.
        :type is_admin: bool
        """

        self._is_admin = is_admin
